-- Creating tables for Covid_ProjectDB
CREATE TABLE House_data (
    zpid INT NOT NULL,
    city VARCHAR NOT NULL,
	streetAddress VARCHAR NOT NULL,
	zipcode INT NOT NULL,
	description VARCHAR NOT NULL,
	latitude DOUBLE PRECISION NOT NULL,
	longitude REAL NOT NULL,
	propertyTaxRate REAL NOT NULL,
	garageSpaces INT NOT NULL,
	hasAssociation INT NOT NULL,
	hasCooling INT NOT NUll,
	hasGarage INT NOT NULL,
	hasHeating INT NOT NULL,
	hasSpa INT NOT NULL,
	hasView INT NOT NULL,
	homeType VARCHAR NOT NULL,
	parkingSpaces INT NOT NULL,
	yearBuilt INT NOT NULL,
	latestPrice REAL NOT NULL,
	numPriceChanges INT NOT NULL,
	latest_saledate DATE NOT NULL,
	latest_salemonth INT NOT NULL,
	latest_saleyear INT NOT NULL, 
	latestPriceSource VARCHAR NOT NULL,
	numOfPhotos INT NOT NULL,
	accessibility INT NOT NULL,
	numOfAppliances INT NOT NULL,
	numOfParkingFeatures INT NOT NULL,
	patioporch INT NOT NULL,
	security INT NOT NULL,
	waterfront INT NOT NULL,
	windowfeatures INT NOT NULL,
	community INT NOT NULL,
	lotSizeSqFt REAL NOT NULL,
	livingAreaSqFt REAL NOT NULL,
	numOfBathrooms REAL NOT NULL,
	numOfBedrooms REAL NOT NULL,
	numOfStories REAL NOT NULL,
	homeImage VARCHAR NOT NULL,
	zip_rank INT NOT NULL,
	median_zip REAL NOT NULL,
	pr_sqft REAL NOT NULL,
    PRIMARY KEY (zpid)
);

CREATE TABLE House_Data2 (
	zpid INT NOT NULL,
	numOfPrimarySchools INT NOT NULL,
	numOfElementarySchools INT NOT NULL,
	numOfMiddleSchools INT NOT NULL,
	numOfHighSchools INT NOT NULL,
	avgSchoolDistance DOUBLE PRECISION NOT NULL,
	avgSchoolRating DOUBLE PRECISION NOT NULL,
	avgSchoolSize INT NOT NULL,
	MedianStudentsPerTeacher INT NOT NULL,
	FOREIGN KEY (zpid) REFERENCES House_Data (zpid),
		PRIMARY KEY (zpid)
);